// This file is auto-generated by @hey-api/openapi-ts

import type { RegisterUserResponse } from './types.gen';

const userSchemaResponseTransformer = (data: any) => {
  data.email_verified_at = new Date(data.email_verified_at);
  data.created_at = new Date(data.created_at);
  data.updated_at = new Date(data.updated_at);
  return data;
};

export const registerUserResponseTransformer = async (data: any): Promise<RegisterUserResponse> => {
  if (data.data) {
    data.data = userSchemaResponseTransformer(data.data);
  }
  return data;
};
