// This file is auto-generated by @hey-api/openapi-ts

export type User = {
  id: number;
  name: string;
  email: string;
  email_verified_at: Date | null;
  created_at: Date;
  updated_at: Date;
};

export type RegisterUserData = {
  body: {
    name: string;
    email: string;
    password: string;
    password_confirmation: string;
  };
  path?: never;
  query?: never;
  url: '/api/auth/register';
};

export type RegisterUserErrors = {
  /**
   * Validation error
   */
  422: {
    success?: boolean;
    message?: string;
    errors?: {
      [key: string]: unknown;
    };
  };
};

export type RegisterUserError = RegisterUserErrors[keyof RegisterUserErrors];

export type RegisterUserResponses = {
  /**
   * User registered successfully
   */
  201: {
    success?: boolean;
    message?: string;
    data?: User;
  };
};

export type RegisterUserResponse = RegisterUserResponses[keyof RegisterUserResponses];

export type ClientOptions = {
  baseURL: 'http://localhost/api' | (string & {});
};
